# Generated by Django 4.0.1 on 2022-01-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('store', '0002_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
