# Generated by Django 4.0.1 on 2022-01-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='supplier', max_length=250),
            preserve_default=False,
        ),
    ]
