# Generated by Django 4.0.1 on 2022-01-09 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0005_userproductrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(related_name='products', through='products.UserProductRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
